CREATE TABLE offers
(
	id character varying(50) NOT NULL,
	name character varying(500) NOT NULL,
	status character varying(50) NOT NULL,
	category character varying(50) ,
	currency character varying(20) ,
	price character varying(200) ,
	model character varying(20) ,
	start_date character varying(30) ,
	end_date character varying(30) ,
	preview_url character varying(1000) ,
	country_allowed character varying(1000) ,
	country_blocked character varying(1000) ,
	city_allowed character varying(1000) ,
	city_blocked character varying(1000) ,
	os_allowed character varying(50) ,
	os_blocked character varying(50) ,
	device_allowed character varying(50) ,
	device_blocked character varying(50) ,
	isp_allowed character varying(50) ,
	isp_blocked character varying(50) ,
	click_url character varying(1000) ,
	impression_url character varying(1000) ,
	redirects character varying(10) ,
	affiliate_status character varying(20) ,
	CONSTRAINT offers_pkey PRIMARY KEY (id)
)