CREATE TABLE offers
(
	id varchar(50) NOT NULL,
	name varchar(500) NOT NULL,
	status varchar(50) NOT NULL,
	category varchar(50) ,
	currency varchar(20) ,
	price varchar(200) ,
	model varchar(20) ,
	start_date varchar(30) ,
	end_date varchar(30) ,
	preview_url varchar(1000) ,
	country_allowed varchar(1000) ,
	country_blocked varchar(1000) ,
	city_allowed varchar(1000) ,
	city_blocked varchar(1000) ,
	os_allowed varchar(50) ,
	os_blocked varchar(50) ,
	device_allowed varchar(50) ,
	device_blocked varchar(50) ,
	isp_allowed varchar(50) ,
	isp_blocked varchar(50) ,
	click_url varchar(1000) ,
	impression_url varchar(1000) ,
	redirects varchar(10) ,
	affiliate_status varchar(20) ,
	CONSTRAINT offers_pkey PRIMARY KEY (id)
);